# Generated by Django 4.1.5 on 2023-06-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Autor')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido del Autor')),
                ('fechaNacimiento', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.ManyToManyField(related_name='autorNacionalidad', to='pais.pais', verbose_name='Pais de Nacimiento')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'Autor',
                'ordering': ['id'],
            },
        ),
    ]
