# Generated by Django 4.1.5 on 2023-06-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('recurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicioPrestamo', models.DateField(verbose_name='Fecha de incio que se realizó el prestamo')),
                ('fechaFinPrestamo', models.DateField(verbose_name='Fecha de devolución del prestamo')),
                ('fechaRealPrestamo', models.DateField(blank=True, null=True, verbose_name='Fecha real que se devolvió el prestamo')),
                ('estadoPrestamo', models.CharField(choices=[('Activo', 'Activo'), ('Devuelto', 'Devuelto'), ('Atrasado', 'Atrasado')], max_length=8, verbose_name='Estado del Prestamo')),
                ('entregaRecurso', models.CharField(choices=[('Pendiente de entregar', 'Pendiente de entregar'), ('Entregado', 'Entregado')], default='Pendiente de entregar', max_length=21, verbose_name='Estado de entrega de recurso')),
                ('fechaEntregaRecurso', models.DateField(blank=True, null=True, verbose_name='Fecha en que se entrego el recurso')),
                ('libroPrestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurso.recurso', verbose_name='Libro Prestado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona', verbose_name='Nombre de Usuario')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'db_table': 'Prestamo',
                'ordering': ['id'],
            },
        ),
    ]
