# Generated by Django 4.1.5 on 2023-06-12 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReservación', models.DateField(verbose_name='Fecha de reservación del recurso')),
                ('estadoReservacion', models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado')], max_length=9, verbose_name='Estado del Prestamo')),
                ('libroReservado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurso.recurso', verbose_name='Libro a Reservar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona', verbose_name='Nombre de Usuario que quiere reservar')),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
                'db_table': 'Reservacion',
                'ordering': ['id'],
            },
        ),
    ]
