# Generated by Django 4.1.5 on 2023-06-12 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('reservacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='estadoReservacion',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado')], max_length=9, verbose_name='Estado de la Reservación'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.persona', verbose_name='Nombre de Usuario que quiere reservar'),
        ),
    ]
