# Generated by Django 4.1.5 on 2023-06-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
        ('categoria', '0001_initial'),
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de Recurso')),
                ('editorial', models.CharField(default='', max_length=200, verbose_name='Editorial del Recurso')),
                ('aniopublicacion', models.IntegerField(default='0', verbose_name='Año de Publicación')),
                ('volumen', models.IntegerField(default='0', verbose_name='Numero de Volumen')),
                ('codigoInterno', models.IntegerField(default='0', verbose_name='Codigo de Biblioteca')),
                ('cantidad', models.IntegerField(default='0')),
                ('autor', models.ManyToManyField(related_name='autorRecurso', to='autor.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.estado')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'Recurso',
                'ordering': ['id'],
            },
        ),
    ]
